# Generated by Django 6.0.5 on 2026-05-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frontend', 'Frontend Engineer'), ('backend', 'Backend Engineer'), ('fullstack', 'Full Stack Engineer'), ('swe', 'Software Engineer'), ('dsa', 'Data Structures & Algorithms')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('total_questions', models.PositiveSmallIntegerField(default=5)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
