# Generated by Django 6.0.5 on 2026-05-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('oops', 'Object Oriented Programming'), ('dbms', 'Database Management'), ('os', 'Operating Systems'), ('networking', 'Computer Networks'), ('react', 'React'), ('django', 'Django'), ('javascript', 'JavaScript'), ('python', 'Python'), ('behavioral', 'Behavioral')], max_length=30)),
                ('text', models.TextField()),
                ('expected_keywords', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
    ]
